// Optional real-browser acceptance. Set NOVA_PLAYWRIGHT and NOVA_CHROME; no production dependency.
const {chromium}=require(process.env.NOVA_PLAYWRIGHT||'playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.NOVA_CHROME?{executablePath:process.env.NOVA_CHROME}:{})});
 const context=await browser.newContext({viewport:{width:1440,height:1000}}),p=await context.newPage(),errors=[],requests=[],records=new Map();let failure=null,viewerRecord=null;
 context.on('page',page=>page.on('pageerror',e=>errors.push(e.message)));p.on('pageerror',e=>errors.push(e.message));
 await context.route('https://**',r=>r.abort());
 await context.exposeBinding('__archiveQA',async(_,address,options)=>{const url=new URL(address),method=options.method||'GET';requests.push({method,path:url.pathname});const result=(data,status=200)=>({data,status});
  if(url.pathname.startsWith('/api/view/'))return result(viewerRecord);
  if(!url.pathname.startsWith('/api/plans'))return result({});
  if(failure&&method==='PUT')return result({error:'Test network conflict'},failure);
  const id=url.pathname.split('/')[3];let data;
  if(method==='PUT'){const body=JSON.parse(options.body);const old=records.get(id);if(old&&old.version!==body.version)return result({error:'Conflict'},409);data={...body,id,version:(old?.version??0)+1,updatedAt:new Date().toISOString(),shared:!!(old?.shared||body.share)};records.set(id,data);}
  else if(id)data=records.get(id);else data={plans:[...records.values()].map(({workspace,...x})=>x)};
  return result(data);
 });
 await context.addInitScript(()=>{globalThis.fetch=async(address,options={})=>{const r=await globalThis.__archiveQA(String(address),{method:options.method,body:options.body});return new Response(JSON.stringify(r.data),{status:r.status,headers:{'Content-Type':'application/json'}});};});
 const url='file:///'+path.resolve('dist/index.html').replace(/\\/g,'/');await p.goto(url);await p.waitForFunction(()=>!!globalThis.HiveArchiveBridge&&!document.getElementById('top-save').disabled);await p.waitForTimeout(100);
 const fingerprint=()=>p.evaluate(()=>HiveRecovery.fingerprint(HiveArchiveBridge.getWorkspace()));
 const original=await fingerprint();
 await p.locator('#plans-menu>summary').click();await p.locator('#new-plan').click();await p.locator('#wizard-title').fill('Cancelled');await p.locator('#wizard-next').click();await p.locator('#wizard-back').click();assert.equal(await p.locator('#wizard-title').inputValue(),'Cancelled');await p.locator('#wizard-cancel').click();assert.equal(await fingerprint(),original);
 await p.locator('#plans-menu>summary').click();await p.locator('#new-plan').click();await p.locator('#wizard-map').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{bad')});await p.locator('[data-wizard-step="2"]').click();await p.locator('#wizard-next').click();assert(await p.locator('#new-plan-dialog').isVisible());assert((await p.locator('#wizard-error').textContent()).length>0);assert.equal(await fingerprint(),original);await p.keyboard.press('Escape');
 await p.evaluate(()=>{const M=HiveModel,W=HiveWorkspace;let s=M.makeLayout('empty',{title:'Acceptance 2.0'});s=M.addPlayers(s,'Harry\nMary').state;s=M.addObject(s,M.makeObject(s,'base',0,0));s=M.assign(s,s.players[0].id,s.objects[0].id);s=M.addObject(s,M.makeObject(s,'missile',10,10));HiveArchiveBridge.load(W.saveFile(W.createWorkspace(s)));});
 await p.locator('#alliance-menu>summary').click();await p.locator('#alliance-add').click();await p.locator('#alliance-edit-name').fill('Second');await p.locator('#alliance-edit-color').fill('#b34466');await p.locator('#alliance-form button.primary').click();assert.equal(await p.locator('#alliance-select option').count(),2);
 await p.locator('#plans-menu>summary').click();await p.locator('#archive-name').fill('Acceptance 2.0');await p.locator('#archive-save').click();await p.waitForFunction(()=>!HiveArchiveBridge.isDirty());assert.equal(records.size,1);const saved=structuredClone([...records.values()][0]);
 await p.locator('#plan-title').fill('Unsaved draft');await p.locator('#plan-title').press('Tab');await p.waitForFunction(()=>HiveArchiveBridge.isDirty());const draft=await fingerprint();assert.equal([...records.values()][0].name,'Acceptance 2.0');assert.equal(JSON.stringify([...records.values()][0].workspace),JSON.stringify(saved.workspace));
 await p.evaluate(async()=>{const row=await HiveRecovery.save(HiveArchiveBridge.getWorkspace(),HiveArchiveBridge.getSource(),true,{force:true});HiveAtelier.previewRecovery(row,()=>{globalThis.previewRestored=true;});});assert(await p.locator('#recovery-preview').isVisible());assert.equal(await p.locator('.recovery-stats dd').last().textContent(),'2');await p.locator('#recovery-preview button').first().click();assert.equal(await fingerprint(),draft);assert.equal(await p.evaluate(()=>!!globalThis.previewRestored),false);
 for(const code of [409,503]){failure=code;await p.locator('#top-save').click();await p.waitForFunction(()=>!document.getElementById('top-save').disabled);assert.equal(await fingerprint(),draft);assert(await p.evaluate(()=>HiveArchiveBridge.isDirty()));assert.equal([...records.values()][0].version,saved.version);}failure=null;
 const writes=requests.filter(x=>x.method!=='GET').length;
 for(const theme of ['night','sage']){await p.locator('#theme-select').evaluate((e,v)=>{e.value=v;e.dispatchEvent(new Event('change'));},theme);for(const lang of ['de','en','fr','es','pt','vi','ko']){await p.locator('#language-select').evaluate((e,v)=>{e.value=v;e.dispatchEvent(new Event('change'));},lang);assert.equal(await fingerprint(),draft);}}
 await p.locator('#language-select').evaluate(e=>{e.value='de';e.dispatchEvent(new Event('change'));});
 for(const width of [1440,1024,768,360,320]){await p.setViewportSize({width,height:1000});await p.evaluate(()=>document.body.classList.add('library-collapsed'));for(const menu of ['plans-menu','settings-menu','map-settings-menu','alliance-menu','display-menu']){await p.locator('#'+menu+'>summary').click();const bounds=await p.locator('#'+menu+'>.menu-content').boundingBox();assert(bounds&&bounds.x>=0&&bounds.x+bounds.width<=width+1,menu+' fits '+width);await p.keyboard.press('Escape');}assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
 assert.equal(requests.filter(x=>x.method!=='GET').length,writes,'navigation never writes the archive');
 await p.setViewportSize({width:1440,height:1000});await p.evaluate(()=>document.body.classList.remove('library-collapsed'));
 // The actual area-fill UI previews first and is undone as one operation.
 await p.locator('#left-tab-objects').click();await p.locator('[data-map-mode=fill]').click();const box=await p.locator('#map').boundingBox();await p.mouse.move(box.x+box.width*.1,box.y+box.height*.1);await p.mouse.down();await p.mouse.move(box.x+box.width*.32,box.y+box.height*.32,{steps:4});await p.mouse.up();await p.waitForFunction(()=>!document.getElementById('apply-area-fill').disabled);const beforeFill=await fingerprint();await p.locator('#apply-area-fill').click();assert.notEqual(await fingerprint(),beforeFill);await p.locator('#undo').click();assert.equal(await fingerprint(),beforeFill);
 await p.locator('#top-save').click();await p.waitForFunction(()=>!HiveArchiveBridge.isDirty());
 viewerRecord=await p.evaluate(()=>({name:'Acceptance viewer',updatedAt:new Date().toISOString(),plan:HiveWorkspace.activePlan(HiveArchiveBridge.getWorkspace())}));
 const viewer=await context.newPage();await viewer.goto('file:///'+path.resolve('viewer/index.html').replace(/\\/g,'/')+'?plan=acceptance');await viewer.waitForFunction(()=>!document.getElementById('map-style').disabled);const readStart=requests.length;await viewer.locator('#map-style').selectOption('game');await viewer.locator('#search').fill('Harry');assert.equal(await viewer.locator('#results button').count(),1);await viewer.locator('#results button').click();const missile=viewer.locator('[data-missile]');await missile.focus();await missile.press('ArrowRight');assert.equal(await viewer.locator('#reset-missiles').isDisabled(),false);await viewer.locator('#reset-missiles').click();assert.equal(await viewer.locator('#reset-missiles').isDisabled(),true);
 for(const width of [1440,768,360,320]){await viewer.setViewportSize({width,height:950});await viewer.locator('#viewer-settings>summary').click();assert(await viewer.locator('#theme-select').isVisible());await viewer.keyboard.press('Escape');assert.equal(await viewer.locator('#theme-select').isVisible(),false);assert(await viewer.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
 assert.equal(requests.slice(readStart).filter(x=>x.method!=='GET').length,0,'viewer has no writes');assert.deepEqual(errors,[]);
 const folder=process.env.NOVA_QA_OUTPUT;if(folder){fs.mkdirSync(folder,{recursive:true});await viewer.setViewportSize({width:1440,height:950});await viewer.screenshot({path:path.join(folder,'viewer.png')});await p.screenshot({path:path.join(folder,'editor.png')});fs.writeFileSync(path.join(folder,'acceptance.json'),JSON.stringify({errors,viewports:[320,360,768,1024,1440],languages:7,archiveRecords:records.size,requests:requests.length,passed:true},null,2));}
 await browser.close();console.log('Passed: wizard cancel/back/invalid import, alliance creation, manual save and drafts, recovery preview, 409/503 data preservation, seven languages, responsive menus, fill preview/undo, viewer search/style/missile/read-only.');
})().catch(e=>{console.error(e);process.exit(1);});
