const assert=require('node:assert/strict');require('../dist/model.js');require('../dist/workspace.js');const M=HiveModel,W=HiveWorkspace;
for(const type of ['base','beacon','center','marshall','stronghold','city','missile']){
 let s=M.makeLayout('empty'),o=M.makeObject(s,type,0,0);s=M.addObject(s,o);assert.deepEqual(M.coords(s,o),{x:500,y:500});assert.deepEqual(M.displayCoords(s,o),{x:500,y:500});s=M.setObjectCenter(s,o.id,820,920);o=s.objects[0];assert.deepEqual(M.displayCoords(s,o),{x:820,y:920});assert.deepEqual(M.cornerCoords(s,o),{x:820-(o.w-1)/2,y:920-(o.h-1)/2});
 s=M.updateObject(s,o.id,{name:'North gate'});assert.equal(M.objectLabel(s,s.objects[0]),'North gate');assert.deepEqual(M.validate(s),s);assert.deepEqual(W.activePlan(W.readFile(W.saveFile(W.createWorkspace(s)))),s);assert.throws(()=>M.setObjectCenter(s,o.id,0,0));
}
let s=M.makeLayout('empty'),o=M.makeObject(s,'terrain');s=M.addObject(s,o);assert.deepEqual(M.displayCoords(s,o),{x:'X',y:'X'});s=M.setObjectCenter(s,o.id,820,920);o=s.objects[0];assert.deepEqual(M.displayCoords(s,o),{x:820,y:920});M.assertWorldPlacement(s,o);s=M.moveObject(s,o.id,o.x+3,o.y-2);assert.deepEqual(M.displayCoords(s,s.objects[0]),{x:823,y:918});assert.deepEqual(M.validate(s),s);s=M.updateObject(s,o.id,{w:5,h:6});assert.equal(M.displayCoords(s,s.objects[0]).y,'X');assert.ok(Number.isInteger(M.displayCoords(s,s.objects[0]).x));
// Connected shapes share their bounding-box center and move together.
let group=M.makeLayout('empty');for(const x of [0,3])group=M.addObject(group,{...M.makeObject(group,'terrain',x,0),x,w:3,h:3,y:0});group=M.connectTerrains(group,group.objects.map(o=>o.id));group=M.setObjectCenter(group,group.objects[1].id,600,700);for(const o of group.objects)assert.deepEqual(M.displayCoords(group,o),{x:600,y:700});assert.equal(group.objects[1].x-group.objects[0].x,3);
// Legacy load changes presentation only; footprints and world calibration are exact.
const old=M.makeLayout();old.version=8;const loaded=M.validate(old);assert.deepEqual(loaded.objects,old.objects);assert.deepEqual(loaded.origin,old.origin);assert.deepEqual(M.coords(loaded,loaded.objects.find(o=>o.type==='center')),{x:500,y:500});
// Custom base names never rename or unassign a roster member.
let named=M.addPlayers(M.makeLayout('empty'),'Harry').state;const base=M.makeObject(named,'base');named=M.addObject(named,base);named=M.assign(named,named.players[0].id,base.id);named=M.updateObject(named,base.id,{name:'Beacon team'});assert.equal(M.objectLabel(named,named.objects[0]),'Beacon team');assert.equal(named.players[0].name,'Harry');assert.equal(named.objects[0].playerId,named.players[0].id);named=M.updateObject(named,base.id,{name:''});assert.equal(M.objectLabel(named,named.objects[0]),'Harry');
const invalid=M.clone(named);invalid.objects[0].name=123;assert.throws(()=>M.validate(invalid));
console.log('Passed: center display/placement for every object, manual X placeholders, whole-tile geometry, compound centers, immutable legacy layout migration, names and all-variant persistence.');
