const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
vm.runInThisContext(fs.readFileSync('dist/model.js','utf8'));
const M=globalThis.HiveModel;
let s=M.makeLayout('spaced');
assert.equal(s.objects.filter(o=>o.type==='base').length,100);
assert.equal(s.objects.filter(o=>o.beacon).length,4);
assert.equal(s.objects.filter(o=>o.type==='marshall').length,1);
for(const o of s.objects)assert.equal(M.collision(s,o),null);
assert.equal(s.objects.filter(o=>o.type==='base'&&M.coverage(s,o).singleFull).length,85);
assert.equal(s.objects.filter(o=>o.type==='base'&&M.coverage(s,o).unionFull).length,100);
let r=M.addPlayers(s,'Sunnyharry\n미스터MM\nĐấu Trường\nSunnyharry');s=r.state;
assert.equal(r.added,3);assert.equal(r.skipped,1);
const a=s.objects.find(o=>o.beacon==='A'),b=s.objects.find(o=>o.beacon==='B'),p=s.players[0];
s=M.assign(s,p.id,a.id);assert.equal(M.playerFor(s,s.objects.find(o=>o.id===a.id)).name,p.name);
s=M.setOrigin(s,600,700);assert.deepEqual(M.coords(s,a),{x:591,y:715});
const shifted=M.moveObject(s,a.id,a.x-1,a.y+1);assert.deepEqual(M.coords(shifted,shifted.objects.find(o=>o.id===a.id)),{x:590,y:716});
assert.throws(()=>M.moveObject(s,a.id,b.x,b.y),/überschneidet/);
assert.throws(()=>M.assign(s,s.players[1].id,a.id),/vergeben/);
let compact=M.makeLayout('compact',s);assert.equal(M.playerFor(compact,compact.objects.find(o=>o.id===a.id)).id,p.id);assert.equal(compact.objects.filter(o=>o.type==='base'&&M.coverage(compact,o).singleFull).length,100);assert.deepEqual(M.coords(compact,compact.objects.find(o=>o.id===a.id)),{x:594,y:712});
let center=s.objects.find(o=>o.type==='center');let moved=M.moveObject(s,center.id,1,0);assert.deepEqual(M.coords(moved,moved.objects.find(o=>o.id===center.id)),{x:601,y:700});assert.deepEqual(M.coords(moved,a),{x:591,y:715});
let noCenter=M.removeObject(moved,center.id);assert.deepEqual(M.coords(noCenter,a),{x:591,y:715});
let terrain=M.makeObject(s,'terrain',30,30);assert.equal(terrain.x,30.5);s=M.addObject(s,terrain);assert.throws(()=>M.addObject(s,M.makeObject(s,'base',30,30)),/überschneidet/);
let round=M.validate(JSON.parse(JSON.stringify(s)));assert.deepEqual(round,s);
let corrupt=M.clone(s);corrupt.objects.find(o=>o.id===b.id).playerId=p.id;assert.throws(()=>M.validate(corrupt),/doppelt/);
corrupt=M.clone(s);corrupt.objects[0].x=1.2;assert.throws(()=>M.validate(corrupt),/Position/);
assert.throws(()=>M.setOrigin(s,1.5,400),/ganze Zahlen/);
assert.equal(M.objectForPlayer(M.removeObject(s,a.id),p.id),null);
assert.equal(M.makeLayout('empty',s).players.length,3);
assert.equal(M.coverage(s,s.objects.find(o=>o.type==='marshall')).singleFull,true);
// Player files: delimiters, names that need CSV quoting, encoding and atomic failure.
assert.deepEqual(M.parsePlayerFile('\uFEFF Alice\r\n\r\n미스터MM\rBob;Clan\n','txt'),['Alice','미스터MM','Bob;Clan']);
assert.deepEqual(M.parsePlayerFile('\uFEFFsep=;\r\nAlice;"Bob;Clan";"Sam ""Ace"""\r\n;미스터MM;\n','csv'),['Alice','Bob;Clan','Sam "Ace"','미스터MM']);
assert.deepEqual(M.parsePlayerFile('  " Alice " ; Bob\rCarol;;\n','csv'),['Alice','Bob','Carol']);
assert.deepEqual(M.parsePlayerFile('"";;\r\n','csv'),[]);
assert.throws(()=>M.parsePlayerFile('Alice;"Bob','csv'),/Anführungszeichen fehlt/);
assert.throws(()=>M.parsePlayerFile('"Alice"oops;Bob','csv'),/Semikolon/);
assert.throws(()=>M.parsePlayerFile('"Alice\nBob"','csv'),/Zeilenumbruch/);
assert.throws(()=>M.parsePlayerFile('Alice','xlsx'),/TXT- oder CSV/);
const unicodeNames='Jörg\n미스터MM\nĐấu Trường';
assert.equal(M.decodePlayerFile(Buffer.from('\uFEFF'+unicodeNames,'utf8')),unicodeNames);
assert.equal(M.decodePlayerFile(Buffer.from('\uFEFF'+unicodeNames,'utf16le')),unicodeNames);
assert.equal(M.decodePlayerFile(Buffer.from('\uFEFF'+unicodeNames,'utf16le').swap16()),unicodeNames);
assert.throws(()=>M.decodePlayerFile(Uint8Array.from([0xc3,0x28])),/UTF-8/);
let imported=M.importPlayers(s,'Sunnyharry;ALICE;Alice;"Bob;Clan";\n','csv');
assert.equal(imported.added,2);assert.equal(imported.skipped,2);
assert.deepEqual(imported.state.players.slice(-2).map(p=>p.name),['ALICE','Bob;Clan']);
assert.deepEqual(imported.state.objects,s.objects);
const beforeImport=M.clone(s);
assert.throws(()=>M.importPlayers(s,'New Player;'+ 'X'.repeat(81),'csv'),/80 Zeichen/);
assert.throws(()=>M.importPlayers(s,Array.from({length:301},(_,i)=>'Member '+i).join(';'),'csv'),/300 Spieler/);
assert.deepEqual(s,beforeImport);

// Autofill: nearest to the center first; preserve manual seats and roster order.
let fill=M.addPlayers(M.makeLayout(),Array.from({length:105},(_,i)=>'Member '+i).join('\n')).state;
const manualBeacon=fill.objects.find(o=>o.beacon==='A'),manualSeat=fill.objects.find(o=>o.type==='base'&&!o.beacon);
fill=M.assign(fill,fill.players[104].id,manualBeacon.id);
fill=M.assign(fill,fill.players[4].id,manualSeat.id);
const beforeFill=M.clone(fill),filled=M.autofill(fill);
assert.equal(filled.assigned,95);assert.equal(filled.remaining,8);assert.equal(filled.reserved,3);
assert.deepEqual(fill,beforeFill);
assert.equal(M.objectForPlayer(filled.state,fill.players[104].id).id,manualBeacon.id);
assert.equal(M.objectForPlayer(filled.state,fill.players[4].id).id,manualSeat.id);
assert.equal(filled.state.objects.filter(o=>o.beacon&&!o.playerId).length,3);
const available=M.autofillOptions(fill).seats;
const distance=(o,ref=fill.origin)=>(o.x-ref.mapX)**2+(o.y-ref.mapY)**2;
assert.ok(distance(available[0])<distance(fill.objects[0]),'The first autofill seat is nearer the center than the top-left seat.');
for(let i=1;i<available.length;i++)assert.ok(distance(available[i-1])<=distance(available[i]));
assert.equal(M.objectForPlayer(filled.state,fill.players[0].id).id,available[0].id);
assert.equal(M.objectForPlayer(filled.state,fill.players[5].id).id,available[4].id);
assert.deepEqual(filled.state.objects.map(({playerId,...o})=>o),fill.objects.map(({playerId,...o})=>o));
assert.deepEqual(filled.state.players,fill.players);
assert.equal(M.autofill(filled.state).state,filled.state);
const withBeacons=M.autofill(filled.state,true);
assert.equal(withBeacons.assigned,3);assert.equal(withBeacons.remaining,5);assert.equal(withBeacons.freeSeats,0);
assert.equal(withBeacons.state.objects.filter(o=>o.type==='base'&&o.playerId).length,100);
assert.deepEqual(M.validate(withBeacons.state),withBeacons.state);
let few=M.addPlayers(M.makeLayout(),'First\nSecond\nThird').state;
assert.equal(M.autofill(few).assigned,3);assert.equal(M.autofill(few).freeSeats,93);
assert.equal(M.autofill(M.makeLayout()).assigned,0);
assert.equal(M.autofill(M.makeLayout('empty',few)).remaining,3);
// Moving the center changes the ranking; changing world coordinates alone does not.
const movedCenter=M.moveObject(few,few.objects.find(o=>o.type==='center').id,1,0);
const movedOrder=M.autofillOptions(movedCenter).seats;
for(let i=1;i<movedOrder.length;i++)assert.ok(distance(movedOrder[i-1],movedCenter.origin)<=distance(movedOrder[i],movedCenter.origin));
const shiftedOrigin=M.setOrigin(few,620,720);
assert.deepEqual(M.autofillOptions(shiftedOrigin).seats.map(o=>o.id),M.autofillOptions(few).seats.map(o=>o.id));
// An individually moved seat outranks its original template index; no center uses the retained origin.
let custom=M.makeLayout('empty');const near=M.makeObject(custom,'base',6,0),far=M.makeObject(custom,'base',50,50);
custom=M.addObject(custom,far);custom=M.addObject(custom,near);
assert.equal(M.autofillOptions(custom).seats[0].id,near.id);
custom=M.moveObject(custom,far.id,0,0);
assert.equal(M.autofillOptions(custom).seats[0].id,far.id);

// Terrain may overlap terrain on creation, movement, resize and re-import.
let ground=M.makeLayout('empty'),t1=M.makeObject(ground,'terrain',0,0),t2=M.makeObject(ground,'terrain',1,1);
ground=M.addObject(ground,t1);ground=M.addObject(ground,t2);
assert.equal(M.overlaps(t1,t2),true);assert.equal(M.collision(ground,t2),null);
ground=M.moveObject(ground,t2.id,t1.x,t1.y);
ground=M.updateObject(ground,t1.id,{w:7,h:2});
let resized=ground.objects.find(o=>o.id===t1.id);
assert.equal(resized.w,7);assert.equal(resized.h,2);
assert.equal(resized.x,M.snap(resized.x,7));assert.equal(resized.y,M.snap(resized.y,2));
assert.deepEqual(M.validate(JSON.parse(JSON.stringify(ground))),ground);
assert.deepEqual(M.validate({...ground,objects:[...ground.objects].reverse()}).objects,[...ground.objects].reverse());
assert.throws(()=>M.updateObject(ground,t1.id,{w:0}),/1 bis 60/);
assert.throws(()=>M.updateObject(ground,t1.id,{h:1.5}),/1 bis 60/);
for(const type of ['base','beacon','center','marshall']){
 const building=M.makeObject(ground,type,0,0);
 assert.throws(()=>M.addObject(ground,building),/überschneidet/);
 let blocked=M.addObject(M.makeLayout('empty'),building);
 assert.throws(()=>M.addObject(blocked,M.makeObject(blocked,'terrain',0,0)),/überschneidet/);
 const far=M.makeObject(blocked,'terrain',-14,0);blocked=M.addObject(blocked,far);
 assert.throws(()=>M.moveObject(blocked,far.id,0,0),/überschneidet/);
 assert.throws(()=>M.moveObject(blocked,building.id,-14,0),/überschneidet/);
 assert.throws(()=>M.updateObject(blocked,far.id,{w:40,h:40}),/überschneidet/);
 const badPlan=M.clone(blocked);Object.assign(badPlan.objects.find(o=>o.id===far.id),{x:.5,y:.5});
 assert.throws(()=>M.validate(badPlan),/überschneidet/);
}
// A rectangle may touch a base edge, and both dimensions change atomically.
let edge=M.makeLayout('empty'),base=M.makeObject(edge,'base',0,0);edge=M.addObject(edge,base);
let touching={...M.makeObject(edge,'terrain',3.5,.5),w:4,h:4};edge=M.addObject(edge,touching);
assert.equal(M.collision(edge,touching),null);
let atomic=M.makeLayout('empty');const high=M.makeObject(atomic,'base',6,5);atomic=M.addObject(atomic,high);
const narrow=M.makeObject(atomic,'terrain',0,0);atomic=M.addObject(atomic,narrow);atomic=M.updateObject(atomic,narrow.id,{w:2,h:12});
assert.throws(()=>M.updateObject(atomic,narrow.id,{w:16}),/überschneidet/);
assert.equal(M.updateObject(atomic,narrow.id,{w:16,h:2}).objects.find(o=>o.id===narrow.id).w,16);
console.log('Passed: original map checks plus TXT/CSV import, UTF-8/UTF-16, atomic failures, autofill preserving manual seats, optional beacon filling, terrain resizing and terrain-only overlaps.');
