const assert=require('node:assert/strict');require('../dist/model.js');require('../dist/workspace.js');const M=HiveModel,Q=HiveQoL,W=HiveWorkspace;
let s=M.makeLayout('empty');for(const [type,x,y] of [['center',0,0],['base',10,0],['base',18,4],['note',10,0]])s=M.addObject(s,M.makeObject(s,type,x,y));
const base=s.objects.find(o=>o.type==='base'),ids=s.objects.filter(o=>o.type==='base').map(o=>o.id),locked=Q.setLocked(s,[base.id],true);
assert.throws(()=>M.moveObject(locked,base.id,40,40));assert.throws(()=>M.removeObjects(locked,ids));assert.throws(()=>M.setOrigin(locked,600,600));assert.throws(()=>M.resetAllianceLayout(locked));assert.deepEqual(M.validate(locked),locked);assert.deepEqual(W.activePlan(W.readFile(W.saveFile(W.createWorkspace(locked)))),locked);
assert.equal(M.moveObject(Q.setLocked(locked,[base.id],false),base.id,40,40).objects.find(o=>o.id===base.id).x,40);
let terrain=M.makeLayout('empty');for(const x of [0,3])terrain=M.addObject(terrain,{...M.makeObject(terrain,'terrain',x,0),x,y:0,w:3,h:3});terrain=M.connectTerrains(terrain,terrain.objects.map(o=>o.id));terrain=Q.setLocked(terrain,[terrain.objects[0].id],true);assert.ok(terrain.objects.every(o=>o.locked));assert.throws(()=>M.resizeTerrain(terrain,terrain.objects[0].id,'ne',9,9));assert.throws(()=>M.disconnectTerrains(terrain,[terrain.objects[0].id]));
// Copies preserve footprints and grouping, strip assignments, get new IDs and respect collisions.
s=M.addPlayers(s,'Alice\nBob').state;s=M.assign(s,s.players[0].id,ids[0]);s=M.assign(s,s.players[1].id,ids[1]);
const swapped=Q.swap(s,ids);assert.equal(swapped.objects.find(o=>o.id===ids[0]).playerId,s.players[1].id);assert.equal(swapped.objects.find(o=>o.id===ids[0]).x,base.x);
const captured=Q.capture(s,ids),copies=Q.prepareCopies(captured),pasted=Q.pasteAt(s,copies,50,50);assert.ok(pasted.ids.every(id=>!s.objects.some(o=>o.id===id)));assert.ok(pasted.state.objects.filter(o=>pasted.ids.includes(o.id)).every(o=>o.playerId===null));assert.equal(pasted.state.objects.length,s.objects.length+2);assert.throws(()=>Q.pasteAt(s,copies,14,2));
const shape=Q.capture(terrain,terrain.objects.map(o=>o.id)),shapeCopies=Q.prepareCopies(shape);assert.equal(shapeCopies[0].terrainGroup,shapeCopies[1].terrainGroup);assert.notEqual(shapeCopies[0].terrainGroup,shape.objects[0].terrainGroup);assert.ok(shapeCopies.every(o=>!o.locked));
const grouped=Q.setGroup(s,ids,'North wing');let library={...grouped,blueprints:[{id:'bp1',name:'Two bases',plan:captured}],viewOptions:{names:false,coordinates:false,notes:false,missiles:false,exportNotes:false,alliances:[1]}};
assert.deepEqual(M.validate(library),library);assert.deepEqual(W.activePlan(W.readFile(W.saveFile(W.createWorkspace(library)))),library);assert.equal(Q.visible(library,s.objects.find(o=>o.type==='note')),false);
const ws=W.switchVariant(W.createWorkspace(library),'off','empty');assert.equal(W.activePlan(ws).blueprints[0].name,'Two bases');
for(const gap of [0,1,2]){const e=Q.arrange(s,ids,'row',gap),next=M.moveObjects(s,e),objects=next.objects.filter(o=>ids.includes(o.id)).sort((a,b)=>a.x-b.x);assert.equal(M.rect(objects[1]).left-M.rect(objects[0]).right,gap);assert.equal(objects[0].y,objects[1].y);}
let checks=M.makeLayout('empty');const note=M.makeObject(checks,'note',0,0);checks=M.addObject(checks,note);checks=M.addObject(checks,M.makeObject(checks,'missile',0,0));const area={left:-1.5,right:1.5,bottom:-1.5,top:1.5};assert.equal(Q.audit(checks,area).totalLandings,1);checks=M.addObject(checks,M.makeObject(checks,'base',0,0));assert.equal(Q.audit(checks,area).totalLandings,0);
let light=M.makeLayout('empty');light=M.addObject(light,M.makeObject(light,'beacon',0,0));for(const x of [5,13,20])light=M.addObject(light,M.makeObject(light,'base',x,0));const a=Q.audit(light);assert.equal(a.full.length,2);assert.equal(a.partial.length,1);assert.equal(a.outside.length,1);
// Whole world scan is bounded; overlaps are candidates, not a count of simultaneously placeable bases.
const scan=Q.audit(M.makeLayout('empty'),{left:-500.5,right:499.5,bottom:-500.5,top:499.5});assert.equal(scan.totalLandings,998*998);assert.equal(scan.landings.length,200);
console.log('Passed: locks across geometry paths, duplicate identity/assignment safety, groups and blueprints round-trip, swapping, exact gaps, visibility, landing scan and light classification.');
