const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
for(const name of ['i18n','world-map','model','workspace'])vm.runInThisContext(fs.readFileSync('dist/'+name+'.js','utf8'));
const M=HiveModel,D=HiveWorldMap,W=HiveWorkspace;
let old=M.makeLayout('empty');old=M.addObject(old,M.makeObject(old,'center',0,0));
const center=old.objects.find(o=>o.type==='center');
assert.equal(M.rechargeArea(center),null);assert.deepEqual(M.validate(old),old,'old plans remain unchanged');
let on=M.updateObject(old,center.id,{showRecharge:true});const o=on.objects[0];
assert.deepEqual(M.rechargeArea(o),{x:0,y:0,w:41,h:41});
assert.deepEqual(M.rechargeBounds(on,o),{left:-20.5,right:20.5,bottom:-20.5,top:20.5});
assert.deepEqual(M.bounds({...on,showLight:false}),M.rechargeBounds(on,o),'fit/export includes recharge even with beacon light hidden');
assert.equal(M.validate(JSON.parse(JSON.stringify(on))).objects[0].showRecharge,true);
assert.equal(W.activePlan(W.readFile(W.saveFile(W.createWorkspace(on)))).objects[0].showRecharge,true);
assert.equal(M.updateObject(on,o.id,{showRecharge:false}).objects[0].showRecharge,false);
assert.throws(()=>M.updateObject(on,o.id,{showRecharge:'yes'}));
assert.throws(()=>M.validate({...on,objects:[{...o,showRecharge:41}]}));
const base=M.makeObject(on,'base',6,0);
assert.doesNotThrow(()=>M.addObject(on,base),'range does not block a base touching the center');
assert.deepEqual(M.coverage(on,base),M.coverage(old,base),'recharge is not beacon coverage');
assert.deepEqual(HiveQoL.audit(on,{left:-25.5,right:25.5,bottom:-25.5,top:25.5}),HiveQoL.audit(old,{left:-25.5,right:25.5,bottom:-25.5,top:25.5}),'landing checks unchanged');
const edge={...on,origin:{x:4,y:4,mapX:0,mapY:0}};
assert.deepEqual(M.rechargeBounds(edge,o),{left:-4.5,right:20.5,bottom:-4.5,top:20.5});
assert.deepEqual(M.rechargeArea(o),{x:0,y:0,w:41,h:41},'world clipping does not change the logical range');
const svg=D.rechargeOverlay(on,o);assert.match(svg,/width="41" height="41"/);assert.match(svg,/pointer-events="none"/);
assert.equal(D.rechargeOverlay(old,center),'');assert.match(D.rechargeOverlay(edge,o),/width="25" height="25"/);
assert.equal(D.centerArtwork(o),'','missing asset falls back to plan rendering');
vm.runInThisContext(fs.readFileSync('dist/map-assets.js','utf8'));
assert.match(HiveMapAssets['alliance-center.webp'],/^data:image\/webp;base64,/);
assert.match(D.centerArtwork(o),/data-center-art="s4"/);
assert.match(D.assetDefinitions(),/id="asset-alliance-center-webp"/);
console.log('Passed: 41×41 range, tile-edge alignment, clipping, old plans, workspace persistence, unchanged collisions/landing/coverage and shared artwork.');
