const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
let saved='sand',callback=0,listener,attribute;const control={addEventListener:(_,f)=>listener=f};const c=vm.createContext({localStorage:{getItem:()=>saved,setItem:(_,v)=>saved=v},document:{documentElement:{setAttribute:(_,v)=>attribute=v},getElementById:()=>control}});vm.runInContext(fs.readFileSync('dist/themes.js','utf8'),c);const T=c.HiveThemes;T.init('theme-select',()=>callback++);assert.equal(attribute,'sand');assert.equal(control.value,'sand');listener({target:{value:'sage'}});assert.equal(saved,'sage');assert.equal(callback,1);assert.equal(T.set('invalid'),false);assert.equal(T.current,'sage');
const luminance=c=>{const rgb=c.slice(1).match(/../g).map(x=>parseInt(x,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return .2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2];};const contrast=(a,b)=>{const x=luminance(a),y=luminance(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05);};
for(const name of Object.keys(T.palettes)){T.set(name);const p=T.palettes[name];for(const text of [p.text,p.muted])for(const bg of [p.bg,p.panel,p.raised])assert.ok(contrast(text,bg)>=4.5,`${name}: ${text} ${bg}`);assert.ok(contrast('#ffffff',p.accent)>=4.5);const raw='<g data-theme-preserve="true"><rect fill="#175ca4"/><text fill="#ffffff">Terrain</text></g><rect fill="#0b1726"/><text fill="#eef7ff">#abcdef Player</text>';const svg=T.svg(raw);assert.ok(svg.includes('fill="#175ca4"'));assert.ok(svg.includes('fill="#ffffff"'));assert.ok(svg.includes('#abcdef Player'));assert.ok(!svg.includes('fill="#0b1726"'));}
T.set('night');const raw='<rect fill="#0b1726"/>';assert.equal(T.svg(raw),raw);
const blocked=vm.createContext({localStorage:{getItem(){throw Error('Blocked');},setItem(){throw Error('Blocked');}},document:{documentElement:{setAttribute(){}},getElementById:()=>control}});vm.runInContext(fs.readFileSync('dist/themes.js','utf8'),blocked);assert.doesNotThrow(()=>blocked.HiveThemes.init('theme-select'));assert.doesNotThrow(()=>blocked.HiveThemes.set('sky'));
console.log('Passed: saved theme selection, switching, invalid values, blocked storage fallback, readable palette contrast, exact dark-theme preservation and protected terrain colors.');
const css=fs.readFileSync('dist/atelier.css','utf8'),rules=[...css.matchAll(/html(?:\[data-theme=([^\]]+)\])?\{([^}]+)\}/g)],base={};
for(const [,name,body] of rules){const palette={...base};for(const [,key,raw] of body.matchAll(/--ui-([a-z-]+):(#[0-9a-f]{3,6})(?=[;}])/g))palette[key]=raw.length===4?'#'+[...raw.slice(1)].map(c=>c+c).join(''):raw;if(!name)Object.assign(base,palette);for(const ink of ['text','muted'])for(const bg of ['bg','panel','raised'])assert.ok(contrast(palette[ink],palette[bg])>=4.5,'Atelier '+(name||'sage')+' '+ink+' on '+bg);assert.ok(contrast(palette.brand,palette['on-brand'])>=4.5,'Atelier primary '+name);}
console.log('Passed: Atelier normal text and primary-action contrast >= 4.5:1 in all four themes.');
