const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const html=fs.readFileSync('viewer/index.html','utf8');for(const match of html.matchAll(/(?:src|href)="([^"#]+)"/g))assert.ok(fs.existsSync(path.resolve('viewer',match[1])),match[1]);
const archive=fs.readFileSync('dist/archive.js','utf8'),share=archive.match(/function shareLink\(id\)\{[^}]+\}/)[0],link=vm.runInNewContext(share+';shareLink("example-id")');assert.equal(link,'https://sunnyharry.github.io/Nova-Hive-Planer/viewer/?plan=example-id');assert.ok(!link.includes('georgiadis'));
const elements=new Map();class El{constructor(){this.value='';this.listeners={};this.dataset={};this.classList={add(){},remove(){}};}addEventListener(k,f){(this.listeners[k]??=[]).push(f);}setAttribute(k,v){this[k]=v;}getBoundingClientRect(){return {left:0,top:0,width:1000,height:700};}setPointerCapture(){}focus(){}closest(){return null;}querySelector(){return new El();}replaceChildren(){}append(){}}
const get=id=>{if(!elements.has(id))elements.set(id,new El());return elements.get(id);};const calls=[];let saved;
const context=vm.createContext({console,document:{getElementById:get,querySelectorAll:()=>[],createElement:()=>new El(),documentElement:{}},ResizeObserver:class{observe(){}},fetch:async(url,opts)=>{calls.push({url,opts});return {ok:true,json:async()=>({name:'Shared map',updatedAt:'2026-09-20T00:00:00Z',plan:saved})};},URLSearchParams,AbortSignal,location:{search:'?plan=example-id'}});
for(const file of ['dist/i18n.js','dist/model.js'])vm.runInContext(fs.readFileSync(file,'utf8'),context);
const M=context.HiveModel;saved=M.makeLayout('empty');saved=M.addObject(saved,M.makeObject(saved,'missile'));
for(const [i,type] of ['base','beacon','center','marshall','terrain','stronghold','city'].entries()){let o=M.makeObject(saved,type,50+i*40,80);if(type==='terrain')o={...o,x:50+i*40,y:80,w:5,h:7};saved=M.addObject(saved,o);}
vm.runInContext(fs.readFileSync('viewer/viewer.js','utf8'),context);
setImmediate(()=>{assert.equal(calls.length,1);assert.equal(calls[0].url,'https://nova-hive-viewer.georgiadis-c.chatgpt.site/api/view/example-id');assert.equal(calls[0].opts.method,undefined);assert.equal(calls[0].opts.headers,undefined);assert.equal(get('title').textContent,'Shared map');assert.match(get('map').innerHTML,/missile-handle/);for(const o of saved.objects){const q=M.displayCoords(saved,o);assert.ok(get('map').innerHTML.includes('X '+q.x));assert.ok(get('map').innerHTML.includes('Y '+q.y));}assert.equal(get('refresh').disabled,false);console.log('Passed: GitHub viewer relative assets, pseudonymous share URL, original plan ID, anonymous read-only API request and rendered missile controls. DOM/fetch doubles.');});
