// QA-only Linkedom integration. No application dependency or visual assertions.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const {parseHTML}=require(process.env.NOVA_DOM_MODULE||'linkedom');
const {window}=parseHTML(fs.readFileSync('dist/index.html','utf8')),document=window.document;
Object.defineProperty(window.HTMLSelectElement.prototype,'value',{get(){return this.querySelector('option[selected]')?.value??this.options[0]?.value??'';},set(v){for(const o of this.options)o.selected=o.value===String(v);},configurable:true});
const P=window.HTMLElement.prototype;P.getBoundingClientRect=()=>({width:1000,height:700,left:0,top:0});P.focus=function(){document.activeElement=this;};P.showModal=function(){this.open=true;};P.close=function(){this.open=false;};P.setCustomValidity=function(){};P.getContext=()=>({measureText:s=>({width:s.length*30})});P.requestSubmit=function(){this.dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true}));};
window.HTMLCanvasElement.prototype.getContext=P.getContext;
const memory=new Map(),c=vm.createContext({document,window,console,localStorage:{getItem:k=>memory.get(k),setItem:(k,v)=>memory.set(k,v)},Blob,URL,setTimeout(){},clearTimeout(){},requestAnimationFrame(){},ResizeObserver:class{observe(){}},TextDecoder});
// Linkedom misreads numeric dataset names (i18n); use the equivalent DOM attribute.
for(const n of ['themes','i18n','model','workspace'])vm.runInContext(fs.readFileSync('dist/'+n+'.js','utf8').replace('el.dataset.i18n',"el.getAttribute('data-i18n')"),c);
let src=fs.readFileSync('dist/app.js','utf8').replace("T.init('theme-select',renderMap);initQoL();","globalThis.testApp={get state(){return state;},commit,selectObject,render,renderInspector};T.init('theme-select',renderMap);initQoL();");vm.runInContext(src,c);
const $=id=>document.getElementById(id),api=c.testApp,M=c.HiveModel,fire=(id,type)=>$(id).dispatchEvent(new window.Event(type,{bubbles:true,cancelable:true})),click=id=>fire(id,'click'),change=(id,v)=>{$(id).value=v;fire(id,'change');},visible=id=>!!$(id)&&!$(id).closest('[hidden]');
function unique(){const ids=[...document.querySelectorAll('[id]')].map(e=>e.id);assert.equal(new Set(ids).size,ids.length,'unique IDs');}
unique();assert.equal($('app-version').textContent,'Version 1.2.0');assert.ok(visible('left-players'));assert.ok(!visible('left-objects'));assert.ok($('inspector-apply').disabled);click('left-tab-objects');assert.ok(visible('object-search'));click('left-tab-blueprints');assert.ok(visible('save-blueprint'));
let s=M.makeLayout('empty');const objs=[];for(const [type,x,y] of [['base',0,0],['base',8,0],['terrain',20,20],['center',40,40]]){const o=M.makeObject(s,type,x,y);objs.push(o);s=M.addObject(s,o);}const [a,b,terrain,center]=objs;api.commit(s);api.selectObject(a.id);assert.ok(visible('object-x'));assert.equal($('object-x').closest('[role=tabpanel]').id,'inspector-pane-position');
const input=$('object-x');input.value='600';fire('object-x','input');input.focus();$('inspector-scroll').scrollTop=45;api.render();assert.equal($('object-x'),input);assert.equal(input.value,'600');assert.equal($('inspector-scroll').scrollTop,45);
click('inspector-tab-properties');assert.ok(visible('object-name-edit'));assert.ok(!visible('object-x'));api.selectObject(terrain.id);assert.ok(visible('terrain-width'));assert.equal($('inspector-tab-properties').getAttribute('aria-selected'),'true');change('object-name-edit','Lake');assert.equal(api.state.objects.find(o=>o.id===terrain.id).name,'Lake');assert.equal($('inspector-name').textContent,'Lake');
click('inspector-tab-actions');assert.ok(visible('qol-copy'));assert.ok(!visible('anchor-section'));click('qol-copy');assert.equal($('qol-paste').disabled,false);api.selectObject(center.id);assert.ok(visible('anchor-section'));click('inspector-tab-position');assert.ok(!visible('anchor-section'));assert.ok(visible('object-x'));
api.selectObject(a.id);api.selectObject(b.id,false,true);assert.ok(visible('selection-x'));assert.ok(!$('object-x'));const q=M.selectionCenter(api.state,[a.id,b.id]).coordinates;change('selection-x',String(q.x+5));change('selection-y',String(q.y+5));click('inspector-apply');assert.equal(M.selectionCenter(api.state,[a.id,b.id]).coordinates.x,q.x+5);
click('inspector-tab-actions');click('qol-lock');assert.ok(api.state.objects.filter(o=>[a.id,b.id].includes(o.id)).every(o=>o.locked));click('qol-unlock');click('left-tab-objects');$('object-search').value='Lake';fire('object-search','input');change('language-select','en');unique();assert.equal($('object-search').value,'Lake');assert.equal($('left-tab-objects').getAttribute('aria-selected'),'true');assert.equal($('inspector-tab-actions').getAttribute('aria-selected'),'true');assert.equal($('inspector-tab-properties').textContent,'Properties');assert.equal($('qol-copy').textContent,'Copy');assert.ok(visible('object-tree'));
click('draw-check-area');assert.ok($('check-drawer').open);click('toggle-hive-check');assert.ok(!$('check-drawer').open);for(const lang of ['fr','es','pt','vi','ko','de']){change('language-select',lang);unique();assert.ok(visible('qol-copy'));}
assert.ok($('archive-name').closest('#plans-menu'));assert.ok($('archive-viewer').closest('.export-menu'));assert.ok($('season-select').closest('.contextbar'));assert.ok($('show-light').closest('#display-menu'));
console.log('Passed: actual HTML DOM, stable tabs/inputs/scroll, center forms, action delegation, locks/copy, archive locations, seven-language rebuilds. No visual browser assertion.');
